"""add_urgency_column

Revision ID: 9819e37260e3
Revises: 38b011bbfdf1
Create Date: 2025-04-28 20:19:16.908482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9819e37260e3'
down_revision = '38b011bbfdf1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('urgency', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'urgency')
    # ### end Alembic commands ### 