"""add_urgency_column

Revision ID: aaaaad185e2e
Revises: 9819e37260e3
Create Date: 2025-04-28 20:27:50.388380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaaaad185e2e'
down_revision = '9819e37260e3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 